import { PrismaClient } from "@prisma/client";
import bcrypt from "bcrypt";

const prisma = new PrismaClient();

async function main() {
  // --- Insert Roles ---
  const roles = [
    { RoleName: "user" },
    { RoleName: "seller" },

  ];

  for (let r of roles) {
    await prisma.roles.upsert({
      where: { RoleName: r.RoleName },
      update: {},
      create: r,
    });
  }

  console.log("Roles inserted.");

  // --- Insert Users ---
  const users = [
    {
      Username: "jaymin thakkar",
      Email: "jaymin8973@gmail.com",
      Password: "Jaymin@2003",
      RoleName: "user",
    },
    {
      Username: "test user",
      Email: "test@gmail.com",
      Password: "123456",
      RoleName: "seller",
    },
  ];

  for (let u of users) {
    const hash = await bcrypt.hash(u.Password, 10);

    const role = await prisma.roles.findUnique({
      where: { RoleName: u.RoleName },
    });

    if (!role) {
      console.log(`Role not found: ${u.RoleName}`);
      continue;
    }

    await prisma.users.upsert({
      where: { Email: u.Email },
      update: {},
      create: {
        Username: u.Username,
        Email: u.Email,
        PasswordHash: hash,
        RoleID: role.RoleID,
      },
    });
  }

  console.log("Users inserted.");

 const products = [
  {
    productName: "Nike Air Zoom Pegasus 40",
    brand: "Nike",
    productType: "Shoes",
    gender: "Male",
    category: "Footwear",
    subcategory: "Running Shoes",
    mrp: "12000",
    sellingPrice: "8999",
    discountPercent: "25",
    sku: "SKU-NIKE-001",
    hsnCode: "6404",
    totalStock: "40",
    shortDescription: "Lightweight running shoe for everyday runners.",
    description: "Breathable mesh upper with responsive ZoomX foam.",
    lowStockAlert: "5",
    metaTitle: "Nike Pegasus 40",
    metaDescription: "Best lightweight running shoes by Nike.",
    tags: "running, nike, sports",
    imageUrl: "https://th.bing.com/th/id/OPAC.fMosbUBeA5aJQw474C474?w=592&h=550&o=5&pid=21.1",
    status: "ACTIVE",
    shippingWeight: "0.8kg",
    packageDimensions: "32x20x12 cm",
    returnPolicy: "7 days return",
    shippingClass: "Standard",
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 1
  },
  {
    productName: "Adidas Ultraboost 23",
    brand: "Adidas",
    productType: "Shoes",
    gender: "Male",
    category: "Footwear",
    subcategory: "Running Shoes",
    mrp: "15000",
    sellingPrice: "10999",
    discountPercent: "27",
    sku: "SKU-ADI-002",
    hsnCode: "6404",
    totalStock: "30",
    shortDescription: "Premium energy-return running shoes.",
    description: "Primeknit upper with Boost cushioning for comfort.",
    lowStockAlert: "5",
    metaTitle: "Adidas Ultraboost 23",
    metaDescription: "Top-tier comfort for long runs.",
    tags: "running, adidas, ultraboost",
    imageUrl: "https://th.bing.com/th?id=OPAC.1o8mofO3Zdv%2fDw474C474&w=592&h=550&o=5&pid=21.1",
    status: "ACTIVE",
    shippingWeight: "0.9kg",
    packageDimensions: "33x22x13 cm",
    returnPolicy: "7 days return",
    shippingClass: "Standard",
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 1
  },
  {
    productName: "Puma Flyer Runner",
    brand: "Puma",
    productType: "Shoes",
    gender: "Female",
    category: "Footwear",
    subcategory: "Sports Shoes",
    mrp: "5000",
    sellingPrice: "3499",
    discountPercent: "30",
    sku: "SKU-PUMA-003",
    hsnCode: "6404",
    totalStock: "60",
    shortDescription: "Stylish lightweight women's running shoes.",
    description: "SoftFoam cushioning with breathable knit upper.",
    lowStockAlert: "8",
    metaTitle: "Puma Flyer Runner",
    metaDescription: "Comfortable and stylish running shoes for women.",
    tags: "puma, running, women",
    imageUrl: "https://th.bing.com/th/id/OPAC.6DH4I1YxGlVYGA474C474?w=592&h=550&o=5&pid=21.1",
    status: "ACTIVE",
    shippingWeight: "0.7kg",
    packageDimensions: "30x18x11 cm",
    returnPolicy: "7 days return",
    shippingClass: "Standard",
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 1
  },
  {
    productName: "Apple AirPods Pro 2nd Gen",
    brand: "Apple",
    productType: "Electronics",
    gender: "Unisex",
    category: "Audio",
    subcategory: "Wireless Earbuds",
    mrp: "26900",
    sellingPrice: "22999",
    discountPercent: "15",
    sku: "SKU-APPLE-004",
    hsnCode: "8518",
    totalStock: "25",
    shortDescription: "Premium ANC earbuds from Apple.",
    description: "Active noise cancellation, transparency mode, adaptive EQ.",
    lowStockAlert: "5",
    metaTitle: "AirPods Pro 2nd Gen",
    metaDescription: "Best ANC earbuds with spatial audio.",
    tags: "apple, airpods, earbuds",
    imageUrl: "https://th.bing.com/th/id/OPAC.C7mfjpdi5vRLcg474C474?w=592&h=550&o=5&pid=21.1",
    status: "ACTIVE",
    shippingWeight: "0.2kg",
    packageDimensions: "10x10x5 cm",
    returnPolicy: "7 days return",
    shippingClass: "Standard",
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 1
  },
  {
    productName: "Samsung Galaxy Watch 6",
    brand: "Samsung",
    productType: "Electronics",
    gender: "Unisex",
    category: "Wearables",
    subcategory: "Smartwatch",
    mrp: "32000",
    sellingPrice: "28490",
    discountPercent: "11",
    sku: "SKU-SAMSUNG-005",
    hsnCode: "8517",
    totalStock: "20",
    shortDescription: "Premium smartwatch with health tracking.",
    description: "AMOLED display with advanced health sensors.",
    lowStockAlert: "5",
    metaTitle: "Galaxy Watch 6",
    metaDescription: "Smartwatch with advanced fitness features.",
    tags: "samsung, smartwatch, wearables",
    imageUrl: "https://th.bing.com/th/id/OPAC.DLaH5IYp0S8tKQ474C474?w=592&h=550&o=5&pid=21.1",
    status: "ACTIVE",
    shippingWeight: "0.3kg",
    packageDimensions: "14x8x6 cm",
    returnPolicy: "7 days return",
    shippingClass: "Standard",
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 1
  },

  // **Add remaining 10 items**
  {
    productName: "Sony WH-1000XM5",
    brand: "Sony",
    productType: "Electronics",
    gender: "Unisex",
    category: "Audio",
    subcategory: "Headphones",
    mrp: "34990",
    sellingPrice: "28999",
    discountPercent: "17",
    sku: "SKU-SONY-006",
    hsnCode: "8518",
    totalStock: "28",
    shortDescription: "Industry-leading noise-cancelling headphones.",
    description: "Exceptional sound quality with LDAC and ANC.",
    lowStockAlert: "5",
    metaTitle: "Sony XM5",
    metaDescription: "Premium ANC headphones.",
    tags: "sony, headphones, anc",
    imageUrl: "https://th.bing.com/th?id=OPAC.geKBb%2bRWGYX5mA474C474&w=592&h=550&o=5&pid=21.1",
    status: "ACTIVE",
    shippingWeight: "0.6kg",
    packageDimensions: "25x20x10 cm",
    returnPolicy: "7 days return",
    shippingClass: "Standard",
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 1
  },
  {
    productName: "Boat Airdopes 141",
    brand: "Boat",
    productType: "Audio",
    gender: "Unisex",
    category: "Audio",
    subcategory: "Wireless Earbuds",
    mrp: "2999",
    sellingPrice: "1299",
    discountPercent: "55",
    sku: "SKU-BOAT-007",
    hsnCode: "8518",
    totalStock: "120",
    shortDescription: "Affordable wireless earbuds with long battery life.",
    description: "42-hour playback with fast charging.",
    lowStockAlert: "10",
    metaTitle: "Boat Airdopes 141",
    metaDescription: "Budget TWS earbuds.",
    tags: "boat, earbuds, tws",
    imageUrl: "https://th.bing.com/th?id=OPAC.0nUEI%2bxAlkNxBA474C474&w=592&h=550&o=5&pid=21.1",
    status: "ACTIVE",
    shippingWeight: "0.12kg",
    packageDimensions: "8x6x4 cm",
    returnPolicy: "7 days return",
    shippingClass: "Standard",
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 1
  },

  {
    productName: "Levi's Slim Fit Jeans",
    brand: "Levi's",
    productType: "Clothing",
    gender: "Male",
    category: "Apparel",
    subcategory: "Jeans",
    mrp: "4999",
    sellingPrice: "3299",
    discountPercent: "34",
    sku: "SKU-LEVIS-008",
    hsnCode: "6203",
    totalStock: "45",
    shortDescription: "Classic slim-fit jeans for men.",
    description: "Stretchable denim for all-day comfort.",
    lowStockAlert: "6",
    metaTitle: "Levi's Slim Fit Jeans",
    metaDescription: "Premium denim jeans for men.",
    tags: "levis, denim, jeans",
    imageUrl: "https://th.bing.com/th/id/OPAC.i6peyChUS4MODQ474C474?w=592&h=550&o=5&pid=21.1",
    status: "ACTIVE",
    shippingWeight: "0.5kg",
    packageDimensions: "35x25x3 cm",
    returnPolicy: "7 days return",
    shippingClass: "Standard",
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 1
  },

  {
    productName: "H&M Floral Summer Dress",
    brand: "H&M",
    productType: "Clothing",
    gender: "Female",
    category: "Apparel",
    subcategory: "Dress",
    mrp: "3499",
    sellingPrice: "2299",
    discountPercent: "34",
    sku: "SKU-HM-009",
    hsnCode: "6204",
    totalStock: "38",
    shortDescription: "Lightweight floral print summer dress.",
    description: "Breathable cotton fabric with modern styling.",
    lowStockAlert: "4",
    metaTitle: "H&M Summer Dress",
    metaDescription: "Floral cotton summer dress.",
    tags: "hm, dress, women",
    imageUrl: "https://th.bing.com/th?id=OPAC.5GQ6wywQ%2f3SwnQ474C474&w=592&h=550&o=5&pid=21.1",
    status: "ACTIVE",
    shippingWeight: "0.35kg",
    packageDimensions: "28x22x4 cm",
    returnPolicy: "7 days return",
    shippingClass: "Standard",
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 1
  },

  {
    productName: "Zara Men's Hoodie",
    brand: "Zara",
    productType: "Clothing",
    gender: "Male",
    category: "Apparel",
    subcategory: "Hoodies",
    mrp: "3999",
    sellingPrice: "2899",
    discountPercent: "28",
    sku: "SKU-ZARA-010",
    hsnCode: "6101",
    totalStock: "32",
    shortDescription: "Premium cotton hoodie.",
    description: "Soft fleece lining with modern fit.",
    lowStockAlert: "5",
    metaTitle: "Zara Hoodie",
    metaDescription: "Men's cotton hoodie.",
    tags: "zara, hoodie, men",
    imageUrl: "https://www.jockey.in/cdn/shop/files/SP17_BLACK_0103_S223_JKY_1.webp?v=1725619829&width=560",
    status: "ACTIVE",
    shippingWeight: "0.7kg",
    packageDimensions: "30x25x6 cm",
    returnPolicy: "7 days return",
    shippingClass: "Standard",
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 1
  },

  {
    productName: "Ray-Ban Aviator Sunglasses",
    brand: "Ray-Ban",
    productType: "Accessories",
    gender: "Unisex",
    category: "Fashion",
    subcategory: "Sunglasses",
    mrp: "8990",
    sellingPrice: "7199",
    discountPercent: "20",
    sku: "SKU-RB-011",
    hsnCode: "9004",
    totalStock: "28",
    shortDescription: "Classic aviator sunglasses.",
    description: "Metal frame with polarized lenses.",
    lowStockAlert: "4",
    metaTitle: "Ray-Ban Aviator",
    metaDescription: "Classic polarized aviator sunglasses.",
    tags: "rayban, sunglasses, aviator",
    imageUrl: "https://cdn.fcglcdn.com/brainbees/images/products/583x720/19639479a.webp",
    status: "ACTIVE",
    shippingWeight: "0.25kg",
    packageDimensions: "18x8x6 cm",
    returnPolicy: "7 days return",
    shippingClass: "Standard",
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 1
  },

  {
    productName: "Fossil Women's Leather Watch",
    brand: "Fossil",
    productType: "Accessories",
    gender: "Female",
    category: "Fashion",
    subcategory: "Watches",
    mrp: "9995",
    sellingPrice: "7999",
    discountPercent: "20",
    sku: "SKU-FOSSIL-012",
    hsnCode: "9102",
    totalStock: "18",
    shortDescription: "Elegant women's leather strap watch.",
    description: "Rose-gold case with genuine leather strap.",
    lowStockAlert: "3",
    metaTitle: "Fossil Women's Watch",
    metaDescription: "Premium leather watch for women.",
    tags: "fossil, watch, women",
    imageUrl: "https://th.bing.com/th/id/OPAC.1kb9NVo7jCH81A474C474?w=592&h=550&o=5&pid=21.1",
    status: "ACTIVE",
    shippingWeight: "0.4kg",
    packageDimensions: "12x12x8 cm",
    returnPolicy: "7 days return",
    shippingClass: "Standard",
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 1
  },

  {
    productName: "Wildcraft Backpack 45L",
    brand: "Wildcraft",
    productType: "Bags",
    gender: "Unisex",
    category: "Accessories",
    subcategory: "Backpacks",
    mrp: "3499",
    sellingPrice: "2699",
    discountPercent: "23",
    sku: "SKU-WC-013",
    hsnCode: "4202",
    totalStock: "50",
    shortDescription: "Durable 45L travel backpack.",
    description: "Water-resistant fabric with multiple compartments.",
    lowStockAlert: "7",
    metaTitle: "Wildcraft Backpack",
    metaDescription: "Travel-ready durable backpack.",
    tags: "wildcraft, backpack, travel",
    imageUrl: "https://cdn.fcglcdn.com/brainbees/images/products/583x720/17582308a.webp",
    status: "ACTIVE",
    shippingWeight: "0.9kg",
    packageDimensions: "50x30x20 cm",
    returnPolicy: "7 days return",
    shippingClass: "Standard",
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 1
  },

  {
    productName: "JBL Flip 6 Bluetooth Speaker",
    brand: "JBL",
    productType: "Electronics",
    gender: "Unisex",
    category: "Audio",
    subcategory: "Bluetooth Speaker",
    mrp: "12990",
    sellingPrice: "10499",
    discountPercent: "19",
    sku: "SKU-JBL-014",
    hsnCode: "8518",
    totalStock: "22",
    shortDescription: "Portable Bluetooth speaker with deep bass.",
    description: "IP67 waterproof with powerful JBL sound.",
    lowStockAlert: "5",
    metaTitle: "JBL Flip 6",
    metaDescription: "Portable waterproof Bluetooth speaker.",
    tags: "jbl, speaker, audio",
    imageUrl: "https://m.media-amazon.com/images/I/61BOdN+QQ2L._AC_SY300_SX300_QL70_FMwebp_.jpg",
    status: "ACTIVE",
    shippingWeight: "0.55kg",
    packageDimensions: "20x12x10 cm",
    returnPolicy: "7 days return",
    shippingClass: "Standard",
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 1
  },

  {
    productName: "Nike Dri-FIT Men’s T-Shirt",
    brand: "Nike",
    productType: "Clothing",
    gender: "Male",
    category: "Apparel",
    subcategory: "T-Shirts",
    mrp: "1999",
    sellingPrice: "1399",
    discountPercent: "30",
    sku: "SKU-NIKE-015",
    hsnCode: "6109",
    totalStock: "55",
    shortDescription: "Moisture-wicking sports T-shirt.",
    description: "Breathable fabric for intense workouts.",
    lowStockAlert: "6",
    metaTitle: "Nike Dri-FIT Tee",
    metaDescription: "Men’s performance T-shirt.",
    tags: "nike, tshirt, men",
    imageUrl: "https://www.jockey.in/cdn/shop/files/AM38_NAVY_0103_S125_JKY_1.webp?v=1716465659&width=560",
    status: "ACTIVE",
    shippingWeight: "0.25kg",
    packageDimensions: "28x20x2 cm",
    returnPolicy: "7 days return",
    shippingClass: "Standard",
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: 1
  }
];

for (const p of products) {
  await prisma.product.create({ data: p });
}

console.log("15 products inserted.");
}

main()
  .then(() => {
    console.log("Seeding complete.");
    prisma.$disconnect();
  })
  .catch((err) => {
    console.error("Error seeding:", err);
    prisma.$disconnect();
  });
